[tool.black]
line-length = 79
target-version = ["py311"]

[tool.isort]
multi_line_output = 3
profile = "black"
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79
