# Generated by Django 5.1.3 on 2024-11-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Program",
            new_name="Info",
        ),
    ]
