# Generated by Django 5.1.3 on 2024-11-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0005_alter_info_options_alter_info_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={"verbose_name": "Program Day"},
        ),
        migrations.AlterModelOptions(
            name="exercise",
            options={"verbose_name": "Program Exercise"},
        ),
    ]
