# Generated by Django 5.1.3 on 2024-11-24 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0006_alter_day_options_alter_exercise_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exercise",
            name="superset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="childset",
                to="program.exercise",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exercise",
            unique_together={("day", "order")},
        ),
    ]
