# Generated by Django 5.1.3 on 2024-11-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0007_exercise_order_exercise_superset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="superset",
        ),
        migrations.AddField(
            model_name="exercise",
            name="is_superset",
            field=models.BooleanField(default=False),
        ),
    ]
