# Generated by Django 5.1.3 on 2024-11-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0008_remove_exercise_superset_exercise_is_superset"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="day",
            unique_together={("program", "week", "day")},
        ),
    ]
