# Generated by Django 5.1.3 on 2024-11-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0009_alter_day_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
