# Generated by Django 5.1.3 on 2024-11-30 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0010_alter_day_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="rpe_percentage",
            new_name="rpe",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="reps",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
