# Generated by Django 5.1.3 on 2024-11-30 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0011_rename_rpe_percentage_exercise_rpe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="rpe_percentage",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="reps",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                    (7, "Seven"),
                    (8, "Eight"),
                    (9, "Nine"),
                    (10, "Ten"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="rpe",
            field=models.FloatField(
                choices=[
                    (6.5, 6.5),
                    (7, 7),
                    (7.5, 7.5),
                    (8, 8),
                    (8.5, 8.5),
                    (9, 9),
                    (9.5, 9.5),
                    (10, 10),
                ],
                null=True,
            ),
        ),
    ]
