# Generated by Django 5.1.3 on 2024-12-01 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "program",
            "0012_exercise_rpe_percentage_alter_exercise_reps_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="rpe",
            field=models.FloatField(
                blank=True,
                choices=[
                    (6.5, 6.5),
                    (7, 7),
                    (7.5, 7.5),
                    (8, 8),
                    (8.5, 8.5),
                    (9, 9),
                    (9.5, 9.5),
                    (10, 10),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="rpe_percentage",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
