# Generated by Django 5.1.3 on 2024-12-03 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0014_alter_exercise_reps_alter_exercise_sets"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="rest",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(600),
                ],
            ),
        ),
    ]
