# Generated by Django 5.1.3 on 2024-11-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="info",
            options={"verbose_name": "Exercise"},
        ),
        migrations.AlterField(
            model_name="bodypart",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="image",
            field=models.ImageField(null=True, upload_to="exercises"),
        ),
        migrations.AlterField(
            model_name="info",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
