# Generated by Django 5.1.3 on 2024-11-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0003_alter_info_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodypart",
            name="hevy_template_id",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="hevy_template_id",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="info",
            name="hevy_template_id",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="bodypart",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Body Part"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Category"
            ),
        ),
    ]
