# Generated by Django 5.1.3 on 2024-11-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "exercise",
            "0004_bodypart_hevy_template_id_category_hevy_template_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bodypart",
            name="hevy_template_id",
        ),
        migrations.RemoveField(
            model_name="category",
            name="hevy_template_id",
        ),
    ]
