# Generated by Django 5.1.3 on 2024-12-01 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0013_exercise_notes_alter_exercise_rpe_and_more"),
        ("user", "0002_alter_profile1rm_options_program"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.day",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Program Day",
                "unique_together": {("user", "program_day")},
            },
        ),
    ]
