# Generated by Django 5.1.3 on 2024-12-01 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0013_exercise_notes_alter_exercise_rpe_and_more"),
        ("user", "0003_programday"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramDayV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.day",
                    ),
                ),
                (
                    "user_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Program Day",
                "unique_together": {("user_program", "program_day")},
            },
        ),
        migrations.DeleteModel(
            name="ProgramDay",
        ),
    ]
