# Generated by Django 5.1.3 on 2024-12-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_programdayv2_delete_programday"),
    ]

    operations = [
        migrations.AddField(
            model_name="programdayv2",
            name="routine_link",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
