# Generated by Django 5.1.3 on 2024-12-01 03:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0013_exercise_notes_alter_exercise_rpe_and_more"),
        ("user", "0005_programdayv2_routine_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramDayExerciseRPEOveride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "override_rpe_percentage",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.programdayv2",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.exercise",
                    ),
                ),
            ],
        ),
    ]
