# Generated by Django 5.1.3 on 2024-12-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_exerciserpeoveride_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="hevy_routine_folder_id",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="programdayv2",
            name="routine_link",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
